// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMFfKSIC5eP8My_4IPAa3YL8z1ith0IXk',
    appId: '1:547929549824:web:e384ee7019f0347d09bce5',
    messagingSenderId: '547929549824',
    projectId: 'delibox-36e5f',
    authDomain: 'delibox-36e5f.firebaseapp.com',
    storageBucket: 'delibox-36e5f.appspot.com',
    measurementId: 'G-ETJV0FXELG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1vbsz_6yb169TBJyZ3WfXJJcrdarrnIs',
    appId: '1:547929549824:android:d289abf08c9239ac09bce5',
    messagingSenderId: '547929549824',
    projectId: 'delibox-36e5f',
    storageBucket: 'delibox-36e5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj96ViKZhW_xdQcci4FPranXxpUhxwFHI',
    appId: '1:547929549824:ios:dacbaea4fb75b23209bce5',
    messagingSenderId: '547929549824',
    projectId: 'delibox-36e5f',
    storageBucket: 'delibox-36e5f.appspot.com',
    iosBundleId: 'com.example.delibox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj96ViKZhW_xdQcci4FPranXxpUhxwFHI',
    appId: '1:547929549824:ios:a87d4dc89a0d816109bce5',
    messagingSenderId: '547929549824',
    projectId: 'delibox-36e5f',
    storageBucket: 'delibox-36e5f.appspot.com',
    iosBundleId: 'com.example.delibox.RunnerTests',
  );
}
